### PR TITLE
finished

### PR DESCRIPTION
**Pull request by Itok2000u**
Finished the code.

### CODE REVIEW

**Comment by ajwang34** [comment]
please link our arxiv submission somewhere

**Comment by ajwang34** [comment]
are we including the code for the experiments in section 5 (further analysis) ?

**Comment by Itok2000u** [comment]
> please link our arxiv submission somewhere in the readme

Yes, In the final section of Readme, there is citation block.

**Comment by Itok2000u** [comment]
> are we including the code for the experiments in section 5 (further analysis) ?

For further analysis, I think we can only include the code for the story generation of Claude. If you think it is necessary, I can include it.

**Comment by danyaljj** [comment]
Thanks @Itok2000u ! 

Merge when @ajwang34 is happy (will now be able to review, unfortunately).

**Pull request merged**
